## Importing and Organizing Your Data in Python - Part I

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

a. Create a series object of 10 randomly generated integer values.

In [1]:
import pandas as pd
import numpy as np

In [18]:
aleatorio = pd.Series(np.random.randint(10, size = 10, dtype = 'int'),name='Test')

In [19]:
aleatorio

0    4
1    9
2    3
3    4
4    9
5    2
6    3
7    9
8    2
9    1
Name: Test, dtype: int64

b. Extract data from IEX for Ford from the 1st of January 2015. The ticker you need is ‘F’.

In [7]:
from pandas_datareader import data as wb

In [21]:
FORD = wb.DataReader('F', data_source='yahoo', start='2015-1-1')

In [22]:
FORD

                 High        Low       Open      Close      Volume  Adj Close
Date
2015-01-02  15.650000  15.180000  15.590000  15.360000  24777900.0  11.837941
2015-01-05  15.130000  14.690000  15.120000  14.760000  44079700.0  11.375521
2015-01-06  14.900000  14.380000  14.880000  14.620000  32981600.0  11.267624
2015-01-07  15.090000  14.770000  14.780000  15.040000  26065300.0  11.591320
2015-01-08  15.480000  15.230000  15.400000  15.420000  33943400.0  11.884183
2015-01-09  15.470000  15.060000  15.460000  15.210000  23420800.0  11.722340
2015-01-12  15.320000  15.110000  15.310000  15.220000  22750800.0  11.730044
2015-01-13  15.480000  15.080000  15.380000  15.210000  26279400.0  11.722340
2015-01-14  15.160000  14.830000  15.070000  15.110000  36798300.0  11.645267
2015-01-15  15.160000  14.800000  15.120000  14.860000  24981300.0  11.452591
2015-01-16  15.040000  14.750000  14.810000  15.020000  32089900.0  11.575904
2015-01-20  15.130000  14.750000  15.080000  15.010000  28553700.0  11.568198
2015-01-21  15.110000  14.880000  14.980000  14.970000  23281500.0  11.537370
2015-01-22  15.070000  14.900000  15.010000  15.030000  23669200.0  11.583611
2015-01-23  15.080000  14.890000  15.020000  14.910000  21620600.0  11.491126
2015-01-26  15.150000  14.970000  14.980000  15.080000  25237200.0  11.622147
2015-01-27  14.990000  14.720000  14.960000  14.850000  34609100.0  11.444886
2015-01-28  14.830000  14.420000  14.830000  14.460000  40579800.0  11.258030
2015-01-29  14.960000  14.300000  14.620000  14.850000  40731100.0  11.561671
2015-01-30  14.890000  14.630000  14.750000  14.710000  30439700.0  11.452671
2015-02-02  15.300000  14.740000  14.750000  15.270000  40371800.0  11.888669
2015-02-03  15.790000  15.440000  15.470000  15.650000  48335400.0  12.184522
2015-02-04  16.020000  15.650000  15.680000  15.870000  41179500.0  12.355804
2015-02-05  16.020000  15.750000  16.010000  15.850000  25713200.0  12.340233
2015-02-06  16.000000  15.770000  15.840000  15.860000  28187700.0  12.348020
2015-02-09  16.030001  15.720000  15.760000  15.920000  20286700.0  12.394732
2015-02-10  16.139999  15.910000  16.049999  16.090000  27928500.0  12.527089
2015-02-11  16.309999  16.010000  16.080000  16.250000  34285300.0  12.651657
2015-02-12  16.450001  16.299999  16.340000  16.360001  23738800.0  12.737304
2015-02-13  16.360001  16.190001  16.330000  16.299999  19954600.0  12.690586
...               ...        ...        ...        ...         ...        ...
2019-06-10  10.030000   9.760000   9.890000   9.820000  33883400.0   9.675588
2019-06-11   9.980000   9.790000   9.870000   9.920000  26434200.0   9.774117
2019-06-12   9.930000   9.840000   9.900000   9.850000  21746700.0   9.705148
2019-06-13  10.060000   9.800000   9.870000  10.060000  25555900.0   9.912059
2019-06-14  10.040000   9.940000  10.010000   9.980000  21553200.0   9.833235
2019-06-17  10.090000   9.940000   9.990000  10.050000  19383800.0   9.902205
2019-06-18  10.200000  10.050000  10.080000  10.100000  32591700.0   9.951470
2019-06-19  10.180000  10.030000  10.150000  10.040000  29051300.0   9.892353
2019-06-20  10.150000   9.950000  10.130000  10.040000  32086500.0   9.892353
2019-06-21  10.050000   9.910000  10.030000   9.990000  47904000.0   9.843088
2019-06-24  10.020000   9.930000   9.950000   9.950000  28091200.0   9.803677
2019-06-25   9.990000   9.830000   9.970000   9.840000  28682000.0   9.695294
2019-06-26   9.960000   9.820000   9.870000   9.910000  33739100.0   9.764264
2019-06-27  10.240000  10.000000  10.040000  10.200000  42954600.0  10.049999
2019-06-28  10.310000  10.200000  10.200000  10.230000  37551600.0  10.079558
2019-07-01  10.430000  10.070000  10.340000  10.150000  38537000.0  10.000734
2019-07-02  10.210000  10.040000  10.150000  10.120000  29708000.0   9.971176
2019-07-03  10.300000  10.130000  10.180000  10.200000  19326600.0  10.049999
2019-07-05  10.270000  10.090000  10.180000  10.200000  21397900.0  10.049999
2019-07-08  10.260000  10.180000  10.200000  10.200000  23244100.0  10.049999
2019-07-09  10.190000  10.100000  10.170000  10.140000  25140600.0   9.990883
2019-07-10  10.260000  10.110000  10.190000  10.110000  29082200.0   9.961323
2019-07-11  10.200000  10.110000  10.150000  10.190000  27667500.0  10.040147
2019-07-12  10.500000  10.240000  10.240000  10.490000  40761600.0  10.335735
2019-07-15  10.560000  10.340000  10.490000  10.420000  33753500.0  10.266765
2019-07-16  10.510000  10.290000  10.370000  10.510000  29530500.0  10.355441
2019-07-17  10.500000  10.310000  10.480000  10.330000  25204400.0  10.178088
2019-07-18  10.310000  10.180000  10.300000  10.260000  25828900.0  10.109118
2019-07-19  10.320000  10.200000  10.300000  10.200000  38501400.0  10.049999
2019-07-22  10.170000  10.050000  10.130000  10.085000  17551205.0  10.085000

[1145 rows x 6 columns]